// Native side of the Push Notifications sample (Android).
//
// Octopus push notifications reach Android as DATA-ONLY FCM messages: neither the OS nor
// Firebase renders them, and Unity's C# is paused while the app is in the background. So
// the notification has to be posted from a native FirebaseMessagingService — this one.
//
// Why a plain .java file and framework-only APIs:
//   - Unity copies Android-enabled .java plugins into the exported Gradle project and
//     compiles them with the app's classpath (Firebase Messaging included). No Kotlin
//     plugin, no extra Gradle wiring, no androidx dependency to declare.
//   - The small icon is the app's launcher icon, so there is no drawable to add. Replace it
//     with a monochrome drawable of your own for a proper status-bar glyph.
//
// The service is registered by OctopusPushSample.androidlib/AndroidManifest.xml with a
// higher intent-filter priority than the Firebase Unity plugin's own service, so FCM hands
// messages to this class instead. It EXTENDS that service (ListenerService, shipped in
// firebase-messaging-cpp.aar) and calls super, so FirebaseMessaging.MessageReceived /
// TokenReceived keep firing in C# exactly as before — the pattern Firebase's own C++/Unity
// sample (MyListenerService) uses. Forwarding an intent with startService() does NOT work:
// FirebaseMessagingService ignores the delivered intent and polls Firebase's internal queue.
package com.octopuscommunity.unitysample.push;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.util.Log;

import com.google.firebase.messaging.RemoteMessage;
import com.google.firebase.messaging.cpp.ListenerService;

import java.util.Map;

public class OctopusMessagingService extends ListenerService {
    private static final String TAG = "OctopusPushSample";

    // Notification channel the Octopus notifications are posted on (created on first use).
    private static final String CHANNEL_ID = "octopus-sdk";
    private static final String CHANNEL_NAME = "Community";

    // Keys of the Octopus data payload — the same ones OctopusSDK.IsOctopusNotification /
    // GetOctopusNotification read on the C# side.
    private static final String KEY_IS_OCTOPUS = "is_octopus_notification";
    private static final String KEY_TITLE = "title";
    private static final String KEY_BODY = "body";

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        Map<String, String> data = remoteMessage.getData();
        if ("true".equalsIgnoreCase(data.get(KEY_IS_OCTOPUS))) {
            showOctopusNotification(remoteMessage);
        }
        // Not an Octopus message: handle your own payloads here.

        // Hand the message to the Firebase Unity plugin (FirebaseMessaging.MessageReceived in
        // C#, plus the pending-message file it replays on next launch).
        super.onMessageReceived(remoteMessage);
    }

    @Override
    public void onNewToken(String token) {
        // FirebaseMessaging.TokenReceived in C#. The sample also calls GetTokenAsync() at
        // startup, so a token is registered even if this fires while the app is not running.
        super.onNewToken(token);
    }

    @SuppressWarnings("deprecation") // Notification.Builder(Context) / setPriority: pre-API 26 path only
    private void showOctopusNotification(RemoteMessage remoteMessage) {
        Map<String, String> data = remoteMessage.getData();

        // Tap target: the app's launcher activity, with the FULL FCM intent extras attached
        // (data keys + "from" + "google.message_id"). With those, the activity generated by the
        // Firebase Unity plugin (MessagingUnityPlayerActivity) forwards the tap to C# as a
        // MessageReceived with NotificationOpened == true, and any activity can read the data
        // keys from getIntent().getExtras() — the C# sample does both.
        Intent launch = getPackageManager().getLaunchIntentForPackage(getPackageName());
        if (launch == null) {
            Log.w(TAG, "No launcher activity found; dropping Octopus notification");
            return;
        }
        launch.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        Intent fcm = remoteMessage.toIntent();
        if (fcm.getExtras() != null) launch.putExtras(fcm.getExtras());

        String messageId = remoteMessage.getMessageId();
        int notificationId = messageId != null ? messageId.hashCode() : (int) System.currentTimeMillis();
        int pendingFlags = PendingIntent.FLAG_UPDATE_CURRENT;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) pendingFlags |= PendingIntent.FLAG_IMMUTABLE;
        PendingIntent contentIntent = PendingIntent.getActivity(this, notificationId, launch, pendingFlags);

        NotificationManager manager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        if (manager == null) return;

        Notification.Builder builder;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(CHANNEL_ID, CHANNEL_NAME, NotificationManager.IMPORTANCE_HIGH);
            manager.createNotificationChannel(channel);
            builder = new Notification.Builder(this, CHANNEL_ID);
        } else {
            builder = new Notification.Builder(this).setPriority(Notification.PRIORITY_HIGH);
        }

        String title = data.get(KEY_TITLE);
        if (title == null || title.isEmpty()) title = getApplicationInfo().loadLabel(getPackageManager()).toString();
        String body = data.get(KEY_BODY);

        builder.setSmallIcon(getApplicationInfo().icon) // replace with a monochrome drawable of yours
               .setContentTitle(title)
               .setContentText(body)
               .setAutoCancel(true)
               .setContentIntent(contentIntent);
        if (body != null) builder.setStyle(new Notification.BigTextStyle().bigText(body));
        manager.notify(notificationId, builder.build());
    }
}
