// Push Notifications Example
//
// Handles Octopus push notifications symmetrically on iOS and Android:
//   tap -> read payload from your push library -> OctopusSDK.GetOctopusNotification(payload)
//        -> OctopusSDK.Open(notification)
//
// iOS uses Unity Mobile Notifications (no native AppController file, no Firebase required).
// Android uses Firebase Messaging (the standard FCM mechanism). Octopus messages are DATA-ONLY on
// Android, so displaying them is the app's job: this sample ships a native
// Plugins/Android/OctopusMessagingService.java (registered by OctopusPushSample.androidlib) that
// posts the notification even while Unity is paused in the background, attaches the payload to
// the tap intent, and extends the Firebase Unity plugin's own service so the Firebase C# events
// keep firing. The C# below only has to detect the tap and hand the payload to the SDK.

#if UNITY_IOS
using Unity.Notifications.iOS;
#endif
#if UNITY_ANDROID
using Firebase.Extensions;
#endif
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PushNotificationsExample : MonoBehaviour
{
    const string API_KEY = "YOUR_API_KEY";

    [SerializeField] Text Message;

    void Start()
    {
        OctopusSDK.Initialize(API_KEY, ConnectionMode.OctopusAuth());
        OctopusSDK.OnNotSeenNotificationsCount += OnNotSeenNotificationCount;
        RegisterForPushNotifications();
#if UNITY_IOS && !UNITY_EDITOR
        HandleIOSColdStartTap();
#elif UNITY_ANDROID && !UNITY_EDITOR
        HandleAndroidLaunchIntent();
#endif
    }

#if UNITY_ANDROID && !UNITY_EDITOR
    // A tap while the app is alive resumes the activity with a new intent (onNewIntent); the
    // activity generated by the Firebase Unity plugin calls setIntent(), so re-reading it on focus
    // covers that case as well as the cold start handled in Start().
    void OnApplicationFocus(bool hasFocus)
    {
        if (hasFocus) HandleAndroidLaunchIntent();
    }
#endif

    void OnDestroy()
    {
        OctopusSDK.OnNotSeenNotificationsCount -= OnNotSeenNotificationCount;
#if UNITY_IOS && !UNITY_EDITOR
        iOSNotificationCenter.OnRemoteNotificationReceived -= OnIOSRemoteNotification;
#endif
    }

    public void OpenOctopus() => OctopusSDK.Open();
    public void UpdateNotificationCount() => OctopusSDK.UpdateNotSeenNotificationsCount();

    public void OnNotSeenNotificationCount(int count)
    {
        Message.text = string.Format("There are {0} unseen notification(s)", count);
        Debug.Log(string.Format("There are {0} unseen notification(s)", count));
    }

    // Shared handler: detect Octopus notification and open it.
    // messageId (Android: FCM's google.message_id) dedupes the two tap paths that can report
    // the same tap — the launch intent's extras and Firebase's MessageReceived(NotificationOpened).
    // Static: survives a scene reload, which would otherwise re-open the still-set launch intent.
    static string _lastHandledMessageId;

    void HandleTappedPayload(IDictionary<string, string> payload, string messageId = null)
    {
        if (!string.IsNullOrEmpty(messageId))
        {
            if (messageId == _lastHandledMessageId) return;
            _lastHandledMessageId = messageId;
        }
        if (OctopusSDK.IsOctopusNotification(payload))
        {
            var notification = OctopusSDK.GetOctopusNotification(payload);
            Debug.Log("Octopus notification tapped, DeepLink: " + notification.DeepLink);
            OctopusSDK.Open(notification);
        }
    }

    void RegisterForPushNotifications()
    {
#if UNITY_IOS && !UNITY_EDITOR
        StartCoroutine(RequestIOSAuthorization());
        iOSNotificationCenter.OnRemoteNotificationReceived += OnIOSRemoteNotification;
#elif UNITY_ANDROID && !UNITY_EDITOR
        InitializeFirebaseForAndroid();
#endif
    }

#if UNITY_IOS
    System.Collections.IEnumerator RequestIOSAuthorization()
    {
        using (var req = new AuthorizationRequest(
            AuthorizationOption.Alert | AuthorizationOption.Sound | AuthorizationOption.Badge,
            registerForRemoteNotifications: true))
        {
            while (!req.IsFinished) yield return null;
            if (req.Granted && !string.IsNullOrEmpty(req.DeviceToken))
                OctopusSDK.RegisterNotificationsToken(req.DeviceToken);
            else
                Debug.LogWarning("iOS notification authorization denied or token unavailable. Error: " + req.Error);
        }
    }

    void HandleIOSColdStartTap()
    {
        var launched = iOSNotificationCenter.GetLastRespondedNotification();
        if (launched != null) HandleTappedPayload(launched.UserInfo);
    }

    void OnIOSRemoteNotification(iOSNotification notification)
    {
        // Fired for notifications received while the app runs; also covers responded taps.
        HandleTappedPayload(notification.UserInfo);
    }
#endif

#if UNITY_ANDROID
    void InitializeFirebaseForAndroid()
    {
        try { RequestAndroidNotificationPermission(); }
        catch (System.Exception e) { Debug.LogWarning("Notification permission request failed: " + e.Message); }

        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
            if (task.Result == Firebase.DependencyStatus.Available)
            {
                Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
                Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
                // TokenReceived only fires on a refresh while the app runs. Fetching the current
                // token here registers it on every launch, refresh missed or not.
                Firebase.Messaging.FirebaseMessaging.GetTokenAsync().ContinueWithOnMainThread(tokenTask => {
                    if (!tokenTask.IsFaulted && !tokenTask.IsCanceled && !string.IsNullOrEmpty(tokenTask.Result))
                        OctopusSDK.RegisterNotificationsToken(tokenTask.Result);
                });
            }
            else Debug.LogError(string.Format("Could not resolve Firebase dependencies: {0}", task.Result));
        });
    }

    void OnTokenReceived(object sender, Firebase.Messaging.TokenReceivedEventArgs token)
        => OctopusSDK.RegisterNotificationsToken(token.Token);

    // Fires for every message (OctopusMessagingService calls super, so the Firebase Unity plugin
    // still sees them) and, with NotificationOpened == true, when the tap intent reaches the
    // plugin's MessagingUnityPlayerActivity. The launch-intent reading below covers custom
    // activities and the cold start too.
    void OnMessageReceived(object sender, Firebase.Messaging.MessageReceivedEventArgs e)
    {
        if (e.Message.NotificationOpened)
            HandleTappedPayload(e.Message.Data, e.Message.MessageId);
    }

#if !UNITY_EDITOR
    // OctopusMessagingService puts the FCM data map (and google.message_id) into the extras of the
    // intent that opens the app on tap. Read it back and hand the Octopus payload to the SDK.
    void HandleAndroidLaunchIntent()
    {
        var payload = new Dictionary<string, string>();
        string messageId = null;
        using (var unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
        using (var activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity"))
        {
            if (activity == null) return;
            using (var intent = activity.Call<AndroidJavaObject>("getIntent"))
            {
                if (intent == null) return;
                using (var extras = intent.Call<AndroidJavaObject>("getExtras"))
                {
                    if (extras == null) return;
                    using (var keys = extras.Call<AndroidJavaObject>("keySet"))
                    using (var iterator = keys.Call<AndroidJavaObject>("iterator"))
                    {
                        while (iterator.Call<bool>("hasNext"))
                        {
                            using (var keyObject = iterator.Call<AndroidJavaObject>("next"))
                            {
                                if (keyObject == null) continue;
                                var key = keyObject.Call<string>("toString");
                                using (var value = extras.Call<AndroidJavaObject>("get", key))
                                {
                                    if (value != null) payload[key] = value.Call<string>("toString");
                                }
                            }
                        }
                    }
                    messageId = extras.Call<string>("getString", "google.message_id");
                }
            }
        }
        if (payload.Count > 0) HandleTappedPayload(payload, messageId);
    }
#endif

    void RequestAndroidNotificationPermission()
    {
        if (GetAndroidSDKInt() >= 33)
        {
            using (var unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
            using (var activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity"))
            {
                const string permission = "android.permission.POST_NOTIFICATIONS";
                if (activity.Call<int>("checkSelfPermission", permission) != 0)
                    activity.Call("requestPermissions", new string[] { permission }, 0);
            }
        }
    }

    int GetAndroidSDKInt()
    {
        using (var version = new AndroidJavaClass("android.os.Build$VERSION"))
            return version.GetStatic<int>("SDK_INT");
    }
#endif
}
