using TMPro;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

/// <summary>The shell's four destinations, in the order SDK_STANDARDS §5.1 fixes them.</summary>
public enum OctopusSampleTab
{
    Home,
    Scenarios,
    Community,
    Settings
}

/// <summary>
/// The sample's shell: one app bar, one content area, one tab bar — the canonical navigation of
/// SDK_STANDARDS §5.1, which every Octopus sample carries.
///
/// **Four tabs, not five.** The canonical order is Home → Scenarios → [Explorer] → Community →
/// Settings, and Explorer is the one platform-conditional tab: Android and iOS only. Its absence
/// here is a contract, not a gap, so nothing in this file is left half-wired for a fifth tab to
/// arrive later. The read-only feature-toggles card the Explorer carried on Android has its own home
/// on Unity, under Settings → Developer tools.
///
/// Built in code, through the shared <see cref="SampleUi"/> builders, for the reason
/// <see cref="OctopusScenariosListView"/> already recorded: a screen that tracks a catalogue living
/// in another repo has to be diffable and reviewable, and serialized YAML is neither. The scene this
/// lives in (`OctopusSample.unity`) therefore holds three objects — a camera, an EventSystem and
/// this component — and is itself generated by `OctopusSampleSceneBuilder`.
///
/// Each tab's content is built on selection and destroyed on leaving it. That is deliberate for a
/// sample: a screen rebuilt from scratch cannot show a stale value from a previous visit, and every
/// tab here is cheap to build. The one thing rebuilding must never do is touch the SDK — the tabs
/// this PR ships make no SDK call at all, and `OctopusSampleShellTests` counts the calls on the
/// sample log seam to keep it that way.
/// </summary>
public class OctopusSampleShell : MonoBehaviour, IOctopusSampleQaNavigation
{
    /// <summary>The scene this shell is the entry point of. Build index 0.</summary>
    public const string SceneName = "OctopusSample";

    /// <summary>The legacy menu scene this shell replaced as the entry point.</summary>
    public const string LegacyMenuScene = "MainMenu";

    /// <summary>
    /// The shell owns the scene, so it draws under every overlay the sample opens over it — the
    /// scenario list at 1000, a scenario screen at 1100.
    /// </summary>
    private const int SortingOrder = 0;

    /// <summary>App bar height: 64dp, the same figure the other samples use.</summary>
    private const float AppBarHeight = OctopusSampleBranding.AppBarUnits;

    /// <summary>Tab bar height: 64dp, so a 48dp target still clears its own padding.</summary>
    private const float TabBarHeight = 192f;

    /// <summary>
    /// How far above the bottom of the screen a floating overlay has to sit to clear the tab bar,
    /// in the canvas units <see cref="SampleUi"/> lays out in.
    ///
    /// Published because the debug console's entry button lives on its own always-on-top canvas and
    /// so cannot see this layout: it sat squarely over the Home tab, hiding the label and leaving
    /// only a sliver of the tab tappable. That is the worst shape of broken — the reader concludes
    /// the app is unresponsive rather than that something is in the way.
    ///
    /// The tab bar is laid out inside the safe area, so the gesture bar is *under* it and its
    /// height has to be added on top; it is in pixels, hence the conversion.
    /// </summary>
    public static float BottomOverlayInsetUnits()
    {
        if (Screen.width <= 0 || Screen.height <= 0) return TabBarHeight;
        var unitsPerPixel = SampleUi.ReferenceWidthFor(SampleUi.ScreenDpWidth()) / Screen.width;
        return TabBarHeight + Screen.safeArea.yMin * unitsPerPixel;
    }

    private static readonly OctopusSampleTab[] Tabs =
    {
        OctopusSampleTab.Home,
        OctopusSampleTab.Scenarios,
        OctopusSampleTab.Community,
        OctopusSampleTab.Settings
    };

    /// <summary>
    /// The name of the transitional route back to the legacy menu scene. Not a catalogue id: the
    /// shared catalogue describes the sample the series is building, not the scenes it is replacing.
    /// </summary>
    public const string LegacyScenesId = "shell-legacy-scenes";

    private OctopusSampleTab _selected = OctopusSampleTab.Home;
    private bool _built;
    private bool _listening;
    private bool _rebuildRequested;
    private RectTransform _content;
    private GameObject _root;
    private OctopusSampleTab _renderedTab;
    private readonly Dictionary<OctopusSampleTab, float> _scrollPositions = new Dictionary<OctopusSampleTab, float>();
    private OctopusScenariosListView.ViewState _listState;
    private RectTransform _appBar;
    private RectTransform _topBleed, _bottomBleed;
    private RectTransform _debugEntry;
    private Transform _debugEntryParent;
    private int _debugBaseSize;
    private float _debugBaseLineHeight;
    private Vector2 _debugAnchorMin, _debugAnchorMax, _debugPivot, _debugSize, _debugPosition;
    private RectOffset _debugEntryPadding;
    private float _debugMinWidth, _debugPreferredWidth, _debugFlexibleWidth;
    private float _debugMinHeight, _debugPreferredHeight, _debugFlexibleHeight;
    private int _debugLayoutPriority;

    public OctopusSampleLocation Location { get; } = new OctopusSampleLocation();

    /// <summary>The tab currently shown.</summary>
    public OctopusSampleTab Selected
    {
        get { return _selected; }
    }

    /// <summary>
    /// Creates the shell over the current scene and builds it immediately. Used by the tests, and by
    /// any caller that needs the shell to exist fully formed the moment the call returns — in
    /// EditMode, `Start` never runs.
    /// </summary>
    public static OctopusSampleShell Create()
    {
        var existing = FindAnyObjectByType<OctopusSampleShell>();
        if (existing != null) return existing;

        var host = new GameObject("OctopusSampleShell");
        var shell = host.AddComponent<OctopusSampleShell>();
        shell.Build();
        return shell;
    }

    /// <summary>
    /// Adds a floating button that leaves the legacy menu for this shell, on its own canvas above
    /// the menu's. Called from `MainMenu.Start` rather than serialized into the scene.
    ///
    /// The transitional bridge out of `MainMenu.unity` and the eight `*Example` scenes (issue
    /// #100): each of those is deleted in the PR that rebuilds its scenario, and this button goes
    /// with the last of them. Its name is deliberately not a catalogue id — `scenarios-tab` names
    /// exactly one object, the tab, and two objects answering to it would make the QA pipeline's
    /// addressing ambiguous.
    /// </summary>
    public static void InstallLegacyMenuEntry()
    {
        if (GameObject.Find("OctopusSampleShellEntry") != null) return;

        var host = new GameObject("OctopusSampleShellEntry");
        // 900: over the menu scene's own canvas. The cost of SampleUi's 1080x1920 reference, shared
        // by every code-built screen here, is that this scales on a slightly different curve from
        // MainMenu.unity's own 800x600 buttons beside it.
        SampleUi.OverlayCanvas(host, 900);

        var safe = SampleUi.SafeArea("SafeArea", host.transform);
        var button = SampleUi.Button("sample-shell-entry", safe, "Sample shell",
                                     () => SceneManager.LoadScene(SceneName));
        button.anchorMin = button.anchorMax = button.pivot = new Vector2(1f, 0f);
        button.sizeDelta = new Vector2(380f, OctopusSampleBranding.MinTouchUnits);
        button.anchoredPosition = new Vector2(-40f, 40f);
    }

    /// <summary>Appearance's theme action, retaining its QA id when Settings mounts it.</summary>
    public static RectTransform BuildThemeToggle(Transform parent)
    {
        RectTransform toggle = null;
        toggle = SampleUi.Button("shell-theme-toggle", parent,
            OctopusSampleBranding.Theme == OctopusSampleTheme.Dark ? "Use light theme" : "Use dark theme",
            SampleUiButtonVariant.Secondary, () =>
            {
                var next = OctopusSampleBranding.Theme == OctopusSampleTheme.Dark
                    ? OctopusSampleTheme.Light : OctopusSampleTheme.Dark;
                toggle.GetComponentInChildren<TMP_Text>().text = next == OctopusSampleTheme.Dark
                    ? "Use light theme" : "Use dark theme";
                OctopusSampleBranding.Theme = next;
            });
        return toggle;
    }

    /// <summary>The catalogue id the QA pipeline taps for <paramref name="tab"/>.</summary>
    public static string TestId(OctopusSampleTab tab)
    {
        switch (tab)
        {
            case OctopusSampleTab.Home: return "home-tab";
            case OctopusSampleTab.Scenarios: return "scenarios-tab";
            case OctopusSampleTab.Community: return "community-tab";
            default: return "settings-tab";
        }
    }

    /// <summary>The app bar title for <paramref name="tab"/>.</summary>
    public static string Title(OctopusSampleTab tab)
    {
        switch (tab)
        {
            // Platform identity belongs to the Home dashboard.
            case OctopusSampleTab.Home: return "Home";
            case OctopusSampleTab.Scenarios: return "Scenarios";
            case OctopusSampleTab.Community: return "Community";
            default: return "Settings";
        }
    }

    /// <summary>
    /// Selects <paramref name="tab"/> and rebuilds the shell around it.
    ///
    /// At runtime the rebuild is deferred by one frame, because the caller is usually the tab
    /// button's own click handler: destroying a <see cref="Button"/> from inside its handler leaves
    /// uGUI holding a destroyed selectable for the pointer-up that follows. In the editor — where
    /// the tests run and no frame ever elapses — it happens immediately instead.
    /// </summary>
    public void Select(OctopusSampleTab tab)
    {
        _selected = tab;
        Location.OpenTab(tab);
        OctopusSampleQaLaunch.Log("tab=" + tab.ToString().ToLowerInvariant());
        if (!_built) return;
        if (Application.isPlaying) _rebuildRequested = true;
        else Rebuild();
    }

    void IOctopusSampleQaNavigation.SelectTab(string id)
    {
        Select((OctopusSampleTab)System.Enum.Parse(typeof(OctopusSampleTab), id, true));
    }

    bool IOctopusSampleQaNavigation.IsTabReady(string id)
    {
        return _built && !_rebuildRequested && _renderedTab.ToString().ToLowerInvariant() == id;
    }

    IOctopusSampleQaScenario IOctopusSampleQaNavigation.OpenScenario(string id)
    {
        var list = _content.GetComponent<OctopusScenariosListView>();
        return list == null ? null : list.OpenScenario(id);
    }

    bool IOctopusSampleQaNavigation.OpenDestination(string id)
    {
        if (id != OctopusSampleQaDestinations.Arcade) return false;
        OctopusReefRunView.Open();
        return true;
    }

    private void Start()
    {
        OctopusSamplePushTokenSource.EnsureExists();
        if (!_built) Build();
        StartCoroutine(OctopusSampleQaLaunch.ShellReady(this));
    }

    private void LateUpdate()
    {
        SampleUi.ResizeBleed(_topBleed, true);
        SampleUi.ResizeBleed(_bottomBleed, false);
        // SafeArea updates its anchors in place, retaining search focus while the keyboard opens.

        if (!_rebuildRequested) return;
        _rebuildRequested = false;
        Rebuild();
    }

    private void OnEnable()
    {
        Listen();
        AttachDebugEntry();
    }

    private void OnDisable() { Shutdown(); }

    public void Shutdown()
    {
        ReleaseDebugEntry();
        StopListening();
    }

    private void OnDestroy()
    {
        ReleaseDebugEntry();
        // Edit mode gets no OnDisable, and a handler left on the static event would fire on a
        // destroyed shell in the next test.
        StopListening();
    }

    /// <summary>
    /// Idempotent, and called from <see cref="Build"/> as well as from <see cref="OnEnable"/>:
    /// Unity does not send OnEnable to a component without <c>[ExecuteAlways]</c> outside play mode,
    /// so a shell created by the EditMode suite would otherwise never hear the theme change it is
    /// there to assert on. The guard is what keeps the two entry points from subscribing twice and
    /// rebuilding the shell twice per toggle at runtime.
    /// </summary>
    private void Listen()
    {
        if (_listening) return;
        OctopusSampleBranding.ThemeChanged += OnThemeChanged;
        SampleUi.DebugEntryChanged += AttachDebugEntry;
        SampleUi.DebugEntryClaimed += OnDebugEntryClaimed;
        _listening = true;
    }

    private void StopListening()
    {
        if (!_listening) return;
        OctopusSampleBranding.ThemeChanged -= OnThemeChanged;
        SampleUi.DebugEntryChanged -= AttachDebugEntry;
        SampleUi.DebugEntryClaimed -= OnDebugEntryClaimed;
        _listening = false;
    }

    private void OnThemeChanged()
    {
        // A destroyed shell can still be holding this handler: the theme event is static, and Unity
        // sends no OnDestroy to a plain MonoBehaviour outside play mode. Drop it here rather than
        // reach for a destroyed transform — the same protection a scene unload needs at runtime.
        if (this == null)
        {
            StopListening();
            return;
        }

        // The same deferral as Select keeps a theme update out of a live click handler.
        if (Application.isPlaying) _rebuildRequested = true;
        else if (_built) Rebuild();
    }

    private void Build()
    {
        _built = true;
        Location.OpenTab(_selected);
        Listen();
        SampleUi.OverlayCanvas(gameObject, SortingOrder);

        // The scene supplies the EventSystem, as everywhere else in this sample: the project is
        // Input-System-only (ProjectSettings activeInputHandler: 1), so the legacy
        // StandaloneInputModule a hand-rolled EventSystem would need throws every frame.
        if (EventSystem.current == null)
        {
            Debug.LogWarning("[Octopus] No EventSystem in this scene — the shell will render but " +
                             "not respond to taps.");
        }

        Rebuild();
    }

    /// <summary>
    /// Tears the shell down and builds it again for the current tab and theme. Everything below the
    /// root is disposable; the component itself and its canvas survive, so the sorting order and the
    /// scene reference stay put.
    /// </summary>
    private void Rebuild()
    {
        CaptureContentState();
        ReleaseDebugEntry();
        if (_root != null)
        {
            // Deactivated before the destroy, not after: at runtime Destroy only takes effect at the
            // end of the frame, and two shells laid out on top of each other for that frame is a
            // flicker a reviewer would file as a bug.
            _root.SetActive(false);
            if (Application.isPlaying) Destroy(_root);
            else DestroyImmediate(_root);
        }

        var root = SampleUi.Panel("Root", transform, SampleUi.Background);
        SampleUi.Stretch(root, Vector2.zero, Vector2.one);
        _root = root.gameObject;

        // The page ground bleeds to the physical edges; the bars' own colours continue into the
        // insets, so a cutout or a gesture bar sits on navy and on the tab bar's surface rather than
        // on a strip of page colour. Only the interactive layout is inset.
        _topBleed = SampleUi.BuildBleed(root, "TopBleed", OctopusSampleBranding.Palette.Chrome, true);
        _bottomBleed = SampleUi.BuildBleed(root, "BottomBleed", OctopusSampleBranding.Palette.Surface, false);

        var safe = BuildSafeArea(root);

        BuildAppBar(safe);
        BuildTabBar(safe);
        BuildContent(safe);
        _renderedTab = _selected;
        Canvas.ForceUpdateCanvases();
        var scroll = _content.GetComponentInChildren<ScrollRect>();
        float position;
        if (scroll != null && _scrollPositions.TryGetValue(_selected, out position))
        {
            LayoutRebuilder.ForceRebuildLayoutImmediate(scroll.content);
            scroll.verticalNormalizedPosition = position;
        }
        AttachDebugEntry();
    }

    private void CaptureContentState()
    {
        if (_content == null) return;
        var scroll = _content.GetComponentInChildren<ScrollRect>();
        if (scroll != null) _scrollPositions[_renderedTab] = scroll.verticalNormalizedPosition;
        var list = _content.GetComponent<OctopusScenariosListView>();
        if (list != null) _listState = list.CaptureState();
    }

    // Adopt the injected control by its existing QA name. No private assembly reference is
    // needed, and removing the Debug folder simply leaves the app bar without this action.
    private void AttachDebugEntry()
    {
        if (this == null)
        {
            StopListening();
            return;
        }
        if (_appBar == null || _debugEntry != null) return;
        var entry = SampleUi.DebugEntry;
        if (entry == null) return;
        // A detail route drawn above the shell holds the entry: a shell rebuild must not pull it
        // back down into the app bar, where the route's own overlay would bury it.
        if (entry.GetComponentInParent<SampleUiDebugEntryHost>() != null) return;
        _debugEntry = entry;
        _debugEntryParent = entry.parent;
        _debugAnchorMin = entry.anchorMin;
        _debugAnchorMax = entry.anchorMax;
        _debugPivot = entry.pivot;
        _debugSize = entry.sizeDelta;
        _debugPosition = entry.anchoredPosition;
        var label = entry.GetComponentInChildren<TMP_Text>();
        if (label != null)
        {
            var scaled = label.GetComponent<SampleUiScaledText>();
            if (scaled != null)
            {
                _debugBaseSize = scaled.BaseSize;
                _debugBaseLineHeight = scaled.BaseLineHeight;
                scaled.Configure(SampleUi.TextBody, OctopusSampleBranding.Dp(20f));
            }
        }
        entry.SetParent(_appBar, false);
        // The app bar is a HorizontalLayoutGroup that controls its children's size and position, so
        // the placement lives in the LayoutElement; anchors written here would be overwritten.
        var element = entry.GetComponent<LayoutElement>();
        if (element == null) element = entry.gameObject.AddComponent<LayoutElement>();
        _debugMinHeight = element.minHeight;
        _debugPreferredHeight = element.preferredHeight;
        _debugFlexibleHeight = element.flexibleHeight;
        _debugLayoutPriority = element.layoutPriority;
        var group = entry.GetComponent<HorizontalOrVerticalLayoutGroup>();
        _debugEntryPadding = group != null
            ? new RectOffset(group.padding.left, group.padding.right, group.padding.top, group.padding.bottom)
            : null;
        _debugMinWidth = element.minWidth;
        _debugPreferredWidth = element.preferredWidth;
        _debugFlexibleWidth = element.flexibleWidth;
        element.minWidth = element.preferredWidth =
            Mathf.Max(OctopusSampleBranding.Dp(80f), SampleUi.PreferredButtonWidth(entry));
        element.flexibleWidth = 0f;
        SampleUi.AppBarItem(entry);
    }

    /// <summary>A detail route's app bar is taking the entry over; hand it back to its owner.</summary>
    private void OnDebugEntryClaimed(object claimant)
    {
        if (this == null)
        {
            StopListening();
            return;
        }
        ReleaseDebugEntry();
    }

    private void ReleaseDebugEntry()
    {
        if (_debugEntry == null) return;
        var label = _debugEntry.GetComponentInChildren<TMP_Text>();
        var scaled = label != null ? label.GetComponent<SampleUiScaledText>() : null;
        if (scaled != null) scaled.Configure(_debugBaseSize, _debugBaseLineHeight);
        var element = _debugEntry.GetComponent<LayoutElement>();
        if (element != null)
        {
            element.minHeight = _debugMinHeight;
            element.preferredHeight = _debugPreferredHeight;
            element.flexibleHeight = _debugFlexibleHeight;
            element.layoutPriority = _debugLayoutPriority;
            element.minWidth = _debugMinWidth;
            element.preferredWidth = _debugPreferredWidth;
            element.flexibleWidth = _debugFlexibleWidth;
        }
        // The persistent owner may already have gone during unload or application shutdown.
        var group = _debugEntry.GetComponent<HorizontalOrVerticalLayoutGroup>();
        if (group != null && _debugEntryPadding != null) group.padding = _debugEntryPadding;
        if (_debugEntryParent == null) { _debugEntry = null; return; }
        _debugEntry.SetParent(_debugEntryParent, false);
        _debugEntry.anchorMin = _debugAnchorMin;
        _debugEntry.anchorMax = _debugAnchorMax;
        _debugEntry.pivot = _debugPivot;
        _debugEntry.sizeDelta = _debugSize;
        _debugEntry.anchoredPosition = _debugPosition;
        _debugEntry = null;
    }

    /// <summary>
    /// The container every interactive element lives in: the screen minus the cutouts, the status
    /// bar and the gesture bar.
    ///
    /// The player is built with `androidRenderOutsideSafeArea: 1`, so without this the app bar's
    /// title sits under the status bar and the tab row under the home indicator — on the emulator
    /// this repo's QA runs on, which has neither, it looks perfectly fine. Anchors rather than
    /// offsets, so the inset is expressed as a fraction of the screen and needs no unit conversion.
    /// </summary>
    private RectTransform BuildSafeArea(RectTransform root)
    {
        return SampleUi.SafeArea("SafeArea", root);
    }

    private void BuildAppBar(RectTransform root)
    {
        var bar = SampleUi.AppBar("AppBar", root, Title(_selected));
        _appBar = bar;
        if (_selected == OctopusSampleTab.Home) OctopusSampleHomeView.BuildPlatformChip(bar);

        // Appearance is owned by Settings; ThemeChanged still rebuilds this shell.
    }

    private void BuildTabBar(RectTransform root)
    {
        var bar = SampleUi.Panel("TabBar", root, OctopusSampleBranding.Palette.Surface);
        bar.anchorMin = Vector2.zero;
        bar.anchorMax = new Vector2(1f, 0f);
        bar.pivot = new Vector2(0.5f, 0f);
        bar.sizeDelta = new Vector2(0f, TabBarHeight);
        bar.anchoredPosition = Vector2.zero;

        var layout = bar.gameObject.AddComponent<HorizontalLayoutGroup>();
        layout.childControlWidth = true;
        layout.childForceExpandWidth = true;
        layout.childControlHeight = true;
        layout.childForceExpandHeight = true;
        layout.padding = new RectOffset(12, 12, 12, 12);
        layout.spacing = 8f;

        foreach (var tab in Tabs) BuildTabItem(bar, tab);
    }

    private void BuildTabItem(RectTransform bar, OctopusSampleTab tab)
    {
        var selected = tab == _selected;
        var palette = OctopusSampleBranding.Palette;

        // GameObject.name IS the catalogue's test id, verbatim — the handle the QA pipeline taps.
        // The indicator is the accent composited at 15% over the bar's own container, posed
        // explicitly (TOKENS §3): 4.74:1 for the label on it in dark theme, the tightest contrast
        // path in the shell, and 12.70:1 in light.
        var item = SampleUi.Panel(TestId(tab), bar, palette.Surface);
        var button = item.gameObject.AddComponent<Button>();
        button.targetGraphic = item.GetComponent<Image>();
        var target = tab;
        button.onClick.AddListener(() => Select(target));

        var element = item.gameObject.AddComponent<LayoutElement>();
        element.minHeight = OctopusSampleBranding.MinTouchUnits;
        element.minWidth = OctopusSampleBranding.MinTouchUnits;
        element.preferredWidth = 0f;
        element.flexibleWidth = 1f;

        var indicator = SampleUi.Panel("Indicator", item,
            selected ? palette.AccentIndicator : palette.Surface,
            OctopusSampleBranding.CardRadius, palette.Surface, 0f);
        indicator.GetComponent<Image>().raycastTarget = false;
        indicator.anchorMin = indicator.anchorMax = indicator.pivot = new Vector2(0.5f, 1f);
        indicator.sizeDelta = new Vector2(OctopusSampleBranding.Dp(56f), OctopusSampleBranding.Dp(32f));
        indicator.anchoredPosition = Vector2.zero;
        BuildTabIcon(indicator, tab, selected ? palette.Accent : palette.Muted);

        var label = SampleUi.Label("Label", item, tab.ToString(), SampleUi.TextCaption,
                                   selected ? palette.Accent : palette.Muted,
                                   TextAnchor.MiddleCenter, tabLabel: true);
        label.fontStyle = selected ? FontStyles.Bold : FontStyles.Normal;
        label.textWrappingMode = TextWrappingModes.Normal;
        var stack = SampleUi.VerticalStack(item, OctopusSampleBranding.Dp(2f), new RectOffset(), false);
        stack.childAlignment = TextAnchor.MiddleCenter;
        stack.childForceExpandWidth = false;
        var iconSize = indicator.gameObject.AddComponent<LayoutElement>();
        iconSize.preferredWidth = OctopusSampleBranding.Dp(56f);
        iconSize.preferredHeight = OctopusSampleBranding.Dp(32f);
        label.gameObject.AddComponent<LayoutElement>().flexibleWidth = 1f;
    }

    // Compose the four navigation pictograms from cached uGUI shapes, independent of font glyphs.
    private static void BuildTabIcon(RectTransform parent, OctopusSampleTab tab, Color ink)
    {
        var icon = SampleUi.Panel("Icon", parent, OctopusSampleBranding.Clear);
        icon.anchorMin = icon.anchorMax = new Vector2(0.5f, 0.5f);
        icon.sizeDelta = Vector2.one * OctopusSampleBranding.Dp(24f);
        icon.anchoredPosition = Vector2.zero;
        float[,] lines;
        switch (tab)
        {
            case OctopusSampleTab.Home:
                lines = new float[,] { { 3, 10, 12, 3 }, { 12, 3, 21, 10 }, { 5, 9, 5, 21 },
                    { 5, 21, 19, 21 }, { 19, 21, 19, 9 }, { 9, 21, 9, 14 },
                    { 9, 14, 15, 14 }, { 15, 14, 15, 21 } };
                break;
            case OctopusSampleTab.Scenarios:
                lines = new float[,] { { 9, 3, 15, 3 }, { 10, 3, 10, 10 }, { 10, 10, 4, 20 },
                    { 4, 20, 20, 20 }, { 20, 20, 14, 10 }, { 14, 10, 14, 3 }, { 7, 15, 17, 15 } };
                break;
            case OctopusSampleTab.Community:
                lines = new float[,] { { 4, 4, 20, 4 }, { 20, 4, 20, 16 }, { 20, 16, 9, 16 },
                    { 9, 16, 4, 20 }, { 4, 20, 4, 4 }, { 8, 8, 16, 8 }, { 8, 12, 13, 12 } };
                break;
            default:
                lines = new float[,] { { 12, 2, 12, 5 }, { 12, 19, 12, 22 }, { 2, 12, 5, 12 },
                    { 19, 12, 22, 12 }, { 5, 5, 7, 7 }, { 17, 17, 19, 19 },
                    { 5, 19, 7, 17 }, { 17, 7, 19, 5 } };
                var ring = SampleUi.Panel("Ring", icon, ink);
                ring.anchorMin = ring.anchorMax = new Vector2(0.5f, 0.5f);
                ring.sizeDelta = Vector2.one * OctopusSampleBranding.Dp(10f);
                ring.anchoredPosition = Vector2.zero;
                var image = ring.GetComponent<Image>();
                image.sprite = SampleUiShapes.Rounded(5f, 2f);
                image.type = Image.Type.Sliced;
                image.raycastTarget = false;
                break;
        }
        for (var i = 0; i < lines.GetLength(0); i++)
        {
            var from = new Vector2(lines[i, 0] - 12f, 12f - lines[i, 1]);
            var to = new Vector2(lines[i, 2] - 12f, 12f - lines[i, 3]);
            var segment = SampleUi.Panel(SampleUi.StrokeName, icon, ink, 1f, ink, 0f);
            segment.GetComponent<Image>().raycastTarget = false;
            segment.anchorMin = segment.anchorMax = new Vector2(0.5f, 0.5f);
            segment.sizeDelta = new Vector2(OctopusSampleBranding.Dp((to - from).magnitude),
                OctopusSampleBranding.Dp(2f));
            segment.anchoredPosition = (from + to) * (0.5f * OctopusSampleBranding.UnitsPerDp);
            segment.localRotation = Quaternion.Euler(0f, 0f,
                Mathf.Atan2(to.y - from.y, to.x - from.x) * Mathf.Rad2Deg);
        }
        string symbol = tab == OctopusSampleTab.Home ? "home"
            : tab == OctopusSampleTab.Scenarios ? "science"
            : tab == OctopusSampleTab.Community ? "forum" : "settings";
        if (SampleUiIcons.Apply(icon.GetComponent<Image>(), symbol, ink))
        {
            // Retain the existing Ring/Stroke objects and names; only their old line rendering
            // is replaced by the exported symbol on Icon. They remain the missing-asset fallback.
            foreach (var oldGraphic in icon.GetComponentsInChildren<Image>())
                if (oldGraphic.transform != icon) oldGraphic.enabled = false;
        }
    }

    private void BuildContent(RectTransform root)
    {
        _content = SampleUi.Panel("Content", root, Color.clear);
        SampleUi.Stretch(_content, Vector2.zero, Vector2.one);
        _content.offsetMin = new Vector2(0f, TabBarHeight);
        _content.offsetMax = new Vector2(0f, -AppBarHeight);

        switch (_selected)
        {
            case OctopusSampleTab.Scenarios:
                OctopusScenariosListView.BuildInto(_content, _listState);
                break;
            case OctopusSampleTab.Home:
                // The dashboard's one action selects a tab rather than calling OctopusSDK.Open:
                // the community door belongs to the Community tab, and one door is what keeps the
                // two from drifting apart.
                OctopusSampleHomeView.BuildInto(_content,
                                                () => Select(OctopusSampleTab.Community));
                break;
            case OctopusSampleTab.Community:
                OctopusSampleCommunityView.BuildInto(_content);
                break;
            default:
                OctopusSampleSettingsView.BuildInto(_content);
                BuildLegacyScenesRoute();
                break;
        }
    }

    // BuildPlaceholder lived here and is gone with the last tab it served. Every one of the four
    // now builds a real screen, so a "Not built yet" card has no caller and no next caller — and a
    // dead private helper is the kind of thing a later reader keeps in the file out of doubt.

    /// <summary>
    /// The route back to `MainMenu.unity` and the legacy `*Example` scenes.
    ///
    /// This shell is build index 0, so nothing loads the menu scene any more, and the bridge
    /// `InstallLegacyMenuEntry` installs only runs *from* it. Without a route in this direction the
    /// four scenes the Scenarios tab does not list — OctopusAuth, ForcedLogin, SSO and
    /// LanguageOverride — are unreachable in the player while their scripts still build: a
    /// regression a compile gate and a scene-count check both report as green. Found in review.
    ///
    /// It goes away with the last of those scenes (issue #100), together with that bridge.
    /// </summary>
    private void BuildLegacyScenesRoute()
    {
        var button = SampleUi.Button(LegacyScenesId, _content, "Legacy demo scenes",
                                     () => SceneManager.LoadScene(LegacyMenuScene));
        button.anchorMin = Vector2.zero;
        button.anchorMax = new Vector2(1f, 0f);
        button.pivot = new Vector2(0.5f, 0f);
        button.offsetMin = new Vector2(40f, 40f);
        button.offsetMax = new Vector2(-40f, 40f + OctopusSampleBranding.MinTouchUnits);
    }
}
